Упражнение 2.1

In [86]:
import numpy as np
from sympy import *

In [10]:
v = Matrix([[-1,4],[-5,2]])
print(det(v))

18


In [12]:
a,b = symbols('a b')
v1 = Matrix([[a+b,a-b],[a+b,a-b]])
print(det(v1))

0


In [14]:
x = symbols('x')
v2 = Matrix([[x,x+1],[-4,x+1]])
print(det(v2))

x**2 + 5*x + 4


Упражнение 2.2

In [15]:
t = Matrix([[1,2,3],[4,5,6],[7,8,1]])
print(det(t))

24


In [16]:
t1 = Matrix([[3,4,-5],[8,7,-2],[2,-1,8]])
print(det(t1))

0


In [17]:
a,b,c,x = symbols('a b c x')
t2 = Matrix([[a+x,x,x],[x,b+x,x],[x,x,c+x]])
print(det(t2))

a*b*c + a*b*x + a*c*x + b*c*x


In [18]:
a,b,c = symbols('a b c')
t3 = Matrix([[sin(a),cos(a),1],[sin(b),cos(b),1],[sin(c),cos(c),1]])
print(det(t3))

sin(a)*cos(b) - sin(a)*cos(c) - sin(b)*cos(a) + sin(b)*cos(c) + sin(c)*cos(a) - sin(c)*cos(b)


Упражнение 2.3

In [25]:
A = np.matrix('3 -5; 2 7')
#print(A)
B = np.matrix('13; 81')
#print(B)
A_det = np.linalg.det(A)
#print(A_det)
if A_det == 0:
    print('det = 0!')
else:
    X_m = np.matrix(A)
    X_m[:, 0] = B
    #print(X_m)
    Y_m = np.matrix(A)
    Y_m[:, 1] = B
    #print(Y_m)
#Z_m = np.matrix(A)
#Z_m[:, 2] = B
#print(Z_m)
    x = round(np.linalg.det(X_m) / A_det)
    y = round(np.linalg.det(Y_m) / A_det)
    X = Matrix([[x],[y]])
    if (np.dot(A,X) - B == 0).all:
        print('Верно')
    else:
        print('Неверно')
#z = np.linalg.det(Z_m) / A_det
    print(x)
    print(y)
#print(z)
#print(np.dot(A,x)-B == 0)

Верно
16
7


In [87]:
A = np.matrix('3 -4; -6 8')
#print(A)
B = np.matrix('-6; 12')
#print(B)
A_det = np.linalg.det(A)
#print(A_det)
if A_det == 0:
    print('det = 0!')
else:
    X_m = np.matrix(A)
    X_m[:, 0] = B
    #print(X_m)
    Y_m = np.matrix(A)
    Y_m[:, 1] = B
    print(Y_m)
    #Z_m = np.matrix(A)
    #Z_m[:, 2] = B
    #print(Z_m)
    x = round(np.linalg.det(X_m) / A_det)
    y = round(np.linalg.det(Y_m) / A_det)
    X = Matrix([[x],[y]])
    if (np.dot(A,X) - B == 0).all:
        print('Верно')
    else:
        print('Неверно')
#z = np.linalg.det(Z_m) / A_det
    print(x)
    print(y)
#print(z)

det = 0!


In [21]:
A = np.matrix('7 2 3; 5 -3 2;10 -11 5')
#print(A)
B = np.matrix('15; 15; 36')
#print(B)
A_det = np.linalg.det(A)
#print(A_det)
if A_det == 0:
    print('Det = 0!')
else:
    X_m = np.matrix(A)
    X_m[:, 0] = B
    #print(X_m)
    Y_m = np.matrix(A)
    Y_m[:, 1] = B
    #print(Y_m)
    Z_m = np.matrix(A)
    Z_m[:, 2] = B
    #print(Z_m)
    x = np.linalg.det(X_m) / A_det
    y = np.linalg.det(Y_m) / A_det
    z = np.linalg.det(Z_m) / A_det
    X = Matrix([[x],[y],[z]])
    if (np.dot(A,X) - B == 0).all:
        print('Верно')
    else:
        print('Неверно')
    print(round(x))
    print(round(y))
    print(round(z))

Верно
2
-1
1


In [88]:
A = np.matrix('2 1 0; 1 0 3;0 5 -1')
#print(A)
B = np.matrix('5; 16; 10')
#print(B)
A_det = np.linalg.det(A)
#print(A_det)
if A_det == 0:
    print('Определитель равен 0')
else:
    X_m = np.matrix(A)
    X_m[:, 0] = B
    #print(X_m)
    Y_m = np.matrix(A)
    Y_m[:, 1] = B
    #print(Y_m)
    Z_m = np.matrix(A)
    Z_m[:, 2] = B
    #print(Z_m)
    x = round(np.linalg.det(X_m) / A_det)
    y = round(np.linalg.det(Y_m) / A_det)
    z = round(np.linalg.det(Z_m) / A_det)
    X = Matrix([[x],[y],[z]])
    print(B)
    print(X)
    print(np.dot(A,X))
    
    if (np.dot(A,X) - B == 0).all:
        print('Верно')
    else:
        print('Неверно')

    print(round(x))
    print(round(y))
    print(round(z))

[[ 5]
 [16]
 [10]]
Matrix([[1], [3], [5]])
[[5]
 [16]
 [10]]
Верно
1
3
5


Упражнение 2.4

In [94]:
A = Matrix([[3, -5],[ 2, 7]])
#print(A)
B = Matrix([[13],[ 81]])
#print(B)
A_det = det(A)
#print(A_det)
if A_det == 0:
    print('det = 0!')
else:
    X_m = Matrix(A)
    X_m[:, 0] = B
    print(X_m)
    Y_m = Matrix(A)
    Y_m[:, 1] = B
    #print(Y_m)
#Z_m = Matrix(A)
#Z_m[:, 2] = B
#print(Z_m)
    x = round(det(X_m) / A_det)
    y = round(det(Y_m) / A_det)
    X = Matrix([[x],[y]])
    #print(np.dot(A,X) - B == 0)
    if (A@X == B):
        print('Верно')
    else:
        print('Неверно')
#z = det(Z_m) / A_det
    print(x)
    print(y)
#print(z)
#print(np.dot(A,x)-B == 0)

Matrix([[13, -5], [81, 7]])
Верно
16
7


In [40]:
A = Matrix([[3, -4],[ -6, 8]])
#print(A)
B = Matrix([[-6],[ 12]])
#print(B)
A_det = det(A)
#print(A_det)
if A_det == 0:
    print('det = 0!')
else:
    X_m = Matrix(A)
    X_m[:, 0] = B
    print(X_m)
    Y_m = Matrix(A)
    Y_m[:, 1] = B
#print(Y_m)
#Z_m = Matrix(A)
#Z_m[:, 2] = B
#print(Z_m)
    x = round(det(X_m) / A_det)
    y = round(det(Y_m) / A_det)
    X = Matrix([[x],[y]])
    if (np.dot(A,X) - B == 0).all:
        print('Верно')
    else:
        print('Неверно')
    #z = det(Z_m) / A_det
    print(x)
    print(y)
#print(z)
#print(np.dot(A,x)-B == 0)

det = 0!


In [93]:
A = Matrix([[7, 2, 3],[ 5, -3, 2], [10, -11, 5]])
B = Matrix([[15],[ 15],[36]])
A_det = det(A)
if A_det == 0:
    print('det = 0!')
else:
    X_m = Matrix(A)
    X_m[:, 0] = B
    #print(X_m)
    Y_m = Matrix(A)
    Y_m[:, 1] = B
    Z_m = Matrix(A)
    Z_m[:, 2] = B
    x = round(det(X_m) / A_det)
    y = round(det(Y_m) / A_det)
    z = round(det(Z_m) / A_det)
    X = Matrix([[x],[y],[z]])
    if (A@X == B):
        print('Верно')
    else:
        print('Неверно')
    print(x)
    print(y)
    print(z)

Верно
2
-1
1


In [91]:
A = Matrix([[2, 1, 0],[ 1, 0, 3], [0, 5, -1]])
#print(A)
B = Matrix([[5],[16],[10]])
#print(B)
A_det = det(A)
#print(A_det)
if A_det == 0:
    print('det = 0!')
else:
    X_m = Matrix(A)
    X_m[:, 0] = B
#print(X_m)
    Y_m = Matrix(A)
    Y_m[:, 1] = B
#print(Y_m)
    Z_m = Matrix(A)
    Z_m[:, 2] = B
#print(Z_m)
    x = round(det(X_m) / A_det)
    y = round(det(Y_m) / A_det)
    z = round(det(Z_m) / A_det)
    X = Matrix([[x],[y],[z]])
    print(X)
    #print(np.dot(A,X))
    print(B)
    #print(np.dot(A,X) - B.transpose()== 0)
    if (A@X == B):
        print('Верно')
    else:
        print('Неверно')
print(x)
print(y)
print(z)
#print(np.dot(A,x)-B == 0)

#Ошибка с Sympy

Matrix([[1], [3], [5]])
Matrix([[5], [16], [10]])
Верно
1
3
5


Упражнение 2.5

In [57]:
A = np.matrix('3 -1 2; 1 4 -1; 2 3 1')
B = np.matrix('-4; 10; 8')
#print(A)
#print(B)
A_inv = np.linalg.inv(A)
#print(A_inv)
X = A_inv.dot(B)
X
if (np.dot(A,X) - B == 0).all:
    print('Верно')
else:
    print('Неверно')

Верно


In [82]:
A = np.matrix('3 -5 ; 2 7 ')
B = np.matrix('13; 81')
#print(A)
#print(B)
A_inv = np.linalg.inv(A)
#print(A_inv)
X = A_inv.dot(B)
print(X)
if (np.dot(A,X) - B == 0).all:
    print('Верно')
else:
    print('Неверно')

[[16.]
 [ 7.]]
Верно


In [77]:
A = np.matrix('3 -4 ; -6 8 ')
B = np.matrix('-6; 12')
#print(A)
#print(B)
if np.linalg.det(A) == 0:
    print('det = 0!')

#print(A_inv)
else:
    A_inv = np.linalg.inv(A)
    X = A_inv.dot(B)
    print(X)
    if (np.dot(A,X) - B == 0).all:
        print('Верно')
    else:
        print('Неверно')

det = 0!


In [83]:
A = np.matrix('7 2 3; 5 -3 2; 10 -11 5')
B = np.matrix('15; 15; 36')
#print(A)
#print(B)
A_inv = np.linalg.inv(A)
#print(A_inv)
X = A_inv.dot(B)
print(X)
if (np.dot(A,X) - B == 0).all:
    print('Верно')
else:
    print('Неверно')

[[ 2.]
 [-1.]
 [ 1.]]
Верно


In [85]:
A = np.matrix('2 1 0; 1 0 3;0 5 -1')
B = np.matrix('5; 16; 10')
#print(A)
#print(B)
A_inv = np.linalg.inv(A)
#print(A_inv)
X = A_inv.dot(B)
print(X)
if (np.dot(A,X) - B == 0).all:
    print('Верно')
else:
    print('Неверно')

[[1.]
 [3.]
 [5.]]
Верно
