In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

1.

In [67]:
A1 = sp.Matrix([[-1,2,0],[2,-1,1],[-4,5,-1],[3,-3,1]])
B1 = sp.Matrix([[-1,2,0],[2,-1,1]])
va1 = sp.Matrix([[4],[1],[3]])
B1 = B1.row_insert(2,sp.Matrix([[1,0,0]]))
XB = B1*va1
print(XB)

Matrix([[-2], [10], [4]])


2.

In [44]:
A2 = sp.Matrix([[1,1,1,1],[1,1,-1,-1],[1,-1,1,-1],[1,-1,-1,1]])
X2 = sp.Matrix([[1],[2],[1],[1]])
T2 = A2.rref()
print(A2*X2)

Matrix([[1, 1, 1, 1], [1, 1, -1, -1], [1, -1, 1, -1], [1, -1, -1, 1]])
Matrix([[5], [1], [-1], [-1]])


3.

In [70]:
A3 = sp.Matrix([[-1,2,0],[2,-1,1],[-4,5,-1],[3,-3,1]])
T3 = A3.rref()
print(T3)

(Matrix([
[1, 0, 2/3],
[0, 1, 1/3],
[0, 0,   0],
[0, 0,   0]]), (0, 1))


4.

In [75]:
L1 = [sp.Matrix([1,1]),sp.Matrix([0,1])]
o1 = sp.GramSchmidt(L1)

L2 = [sp.Matrix([1,1,1]),sp.Matrix([2,1,2]),sp.Matrix([-3,0,2])]
o2 = sp.GramSchmidt(L2)

sp.pprint(o1)
sp.pprint(o2)

V1 = sp.Matrix([[2],[4]])
V2 = sp.Matrix([[5],[3],[1]])

A41 = np.matrix('1 1;-0.5 0.5')
A42 = np.matrix('6 6 6;2 -4 2;-15 0 15')
B41 = np.matrix('2;4')
B42 = np.matrix('30;18;6')
A1_inv = np.linalg.inv(A41)
A2_inv = np.linalg.inv(A42)
X1 = A1_inv.dot(B41)
print('X1: ',X1)
X2 = A2_inv.dot(B42)
print('X2: ',X2)

⎡⎡1⎤  ⎡-1/2⎤⎤
⎢⎢ ⎥, ⎢    ⎥⎥
⎣⎣1⎦  ⎣1/2 ⎦⎦
⎡⎡1⎤  ⎡1/3 ⎤  ⎡-5/2⎤⎤
⎢⎢ ⎥  ⎢    ⎥  ⎢    ⎥⎥
⎢⎢1⎥, ⎢-2/3⎥, ⎢ 0  ⎥⎥
⎢⎢ ⎥  ⎢    ⎥  ⎢    ⎥⎥
⎣⎣1⎦  ⎣1/3 ⎦  ⎣5/2 ⎦⎦
X1:  [[-3.]
 [ 5.]]
X2:  [[ 2.96666667]
 [-1.33333333]
 [ 3.36666667]]


5.

In [60]:
A5 = sp.Matrix([[8,4],[5,2]])
T5 = sp.Matrix([[2,1],[6,4]])
T5m = T5.inv()
A5m = T5m*A5*T5
print(A5m)

Matrix([[69, 83/2], [-98, -59]])


6.

In [63]:
A6 = sp.Matrix([[1,2,0,1],[3,0,-1,2],[2,5,3,1],[1,2,1,3]])
T6 = sp.Matrix([[1,0,0,0],[1,1,0,0],[1,1,1,0],[1,1,1,1]])
T6m = T6.inv()
A6m = T6m * A6 * T6
print(A6m)

Matrix([[4, 3, 1, 1], [0, -2, 0, 1], [7, 8, 3, -1], [-4, -3, 0, 2]])


7.

In [66]:
A = sp.Matrix([[-1, 1, 2], [1, 1, -2], [1, 1, 4]])
B = np.matrix('1, -2, 1; -1, 2, 1; -1, 3, 1')
BB = np.matrix('1, 0, 2; 3, 0, -2; 3, -1, -1')
B_inv = np.linalg.inv(B)
NB = B_inv * BB
NB_inv = np.linalg.inv(NB)

sp.pprint(NB_inv * NB * A)

[[-1. -2.  4.]
 [ 0. -1.  1.]
 [ 2.  0.  0.]]
⎡-1.0  1.0  2.0 ⎤
⎢               ⎥
⎢1.0   1.0  -2.0⎥
⎢               ⎥
⎣1.0   1.0  4.0 ⎦


C1

In [73]:
LC1 = [sp.Matrix([1,1,1,1]),sp.Matrix([3,3,-1,-1]),sp.Matrix([-2,0,6,8])]
LC2 = [sp.Matrix([1,2,2,-1]),sp.Matrix([1,1,-5,3]),sp.Matrix([3,2,8,-7])]
oc1 = sp.GramSchmidt(LC1)
oc2 = sp.GramSchmidt(LC2)
sp.pprint(oc1)
sp.pprint(oc2)

⎡⎡1⎤  ⎡2 ⎤  ⎡-1⎤⎤
⎢⎢ ⎥  ⎢  ⎥  ⎢  ⎥⎥
⎢⎢1⎥  ⎢2 ⎥  ⎢1 ⎥⎥
⎢⎢ ⎥, ⎢  ⎥, ⎢  ⎥⎥
⎢⎢1⎥  ⎢-2⎥  ⎢-1⎥⎥
⎢⎢ ⎥  ⎢  ⎥  ⎢  ⎥⎥
⎣⎣1⎦  ⎣-2⎦  ⎣1 ⎦⎦
⎡⎡1 ⎤  ⎡2 ⎤  ⎡2 ⎤⎤
⎢⎢  ⎥  ⎢  ⎥  ⎢  ⎥⎥
⎢⎢2 ⎥  ⎢3 ⎥  ⎢-1⎥⎥
⎢⎢  ⎥, ⎢  ⎥, ⎢  ⎥⎥
⎢⎢2 ⎥  ⎢-3⎥  ⎢-1⎥⎥
⎢⎢  ⎥  ⎢  ⎥  ⎢  ⎥⎥
⎣⎣-1⎦  ⎣2 ⎦  ⎣-2⎦⎦
