In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math	
import sympy as sp
from matplotlib import cm
from sympy.abc import x,y,z,alpha,beta,pi,n
from matplotlib import style
from scipy import optimize

1.

In [6]:
pol = [1,0,0,-3.2,3,0,3]

arg = [-1,4,2.2,np.pi]

for i in arg:
    print(f"Значение полинома в точке x = {i}: {np.polyval(pol,i)}")

Значение полинома в точке x = -1: 10.2
Значение полинома в точке x = 4: 3942.2
Значение полинома в точке x = 2.2: 96.82630400000005
Значение полинома в точке x = 3.141592653589793: 894.777921401613


2.

In [5]:
pol2 = [2,0,0,-3,0,0,7,0,-2]

for i in np.roots(pol2):
    print(f"{i:.3f}")

-1.017+0.742j
-1.017-0.742j
-0.211+1.245j
-0.211-1.245j
1.084+0.441j
1.084-0.441j
0.289+0.000j


3.

In [8]:
pol31 = [1,2,0,0,-3,0,4]
pol32 = [1,0,-3,1]

print(np.convolve(pol31,pol32))
print(np.polydiv(pol31,pol32))

[  1   2  -3  -5  -1   0  13  -3 -12   4]
(array([1., 2., 3., 5.]), array([ 4., 12., -1.]))


4.

In [19]:
def poly_summ(p1,p2):
    l1 = len(p1); l2 = len(p2)
    if l1 > l2:
        buf = np.zeros(l1-l2)
        pb = np.concatenate((buf,p2),axis=None)
        return p1+pb
    elif l2 > l1:
        buf = np.zeros(l2-l1)
        pb = np.concatenate((buf,p1),axis=None)
        return pb+p2
    else:
        return p1+p2
    
p41 = np.array([1,2,0,0,-3,0,1])
p42 = np.array([1,0,-3,1])

print(poly_summ(p41,p42))

[ 1.  2.  0.  1. -3. -3.  2.]


5.

In [21]:
p51 = [1,-1,0,-3,0,-2]
p52 = [1,0,0,0,0,-3,1]
q51 = np.polyder(p51)
q52 = np.polyder(p52)
pc5 = np.convolve(p51,p52)
pd5 = np.polydiv(p51,p52)
print(q51)
print(q52)
print(pc5)
print(pd5)

[ 5 -4  0 -6  0]
[ 6  0  0  0  0 -3]
[ 1 -1  0 -3  0 -5  4 -1  9 -3  6 -2]
(array([0.]), array([ 1., -1.,  0., -3.,  0., -2.]))


6.

In [29]:
def polydiff(p,n):
    for i in range(1,n+1):
        p = np.polyder(p)
    print(p)
    print(np.polyval(p,0.2))

p6 = [1,0,0,-1,0,0,0,0,3,0,-2]
polydiff(p6,5)

[30240     0     0 -2520     0     0]
-91.1232


7.

In [ ]:
def TaylorCoeffs(pol, point):
    b_k = []
    c = 0
    while np.any(pol) != 0:
        b_k.append(np.polyval(pol, point) / np.math.factorial(c))
        pol = np.polyder(pol)
        c += 1
    return b_k
 
pol = [1, 0, 2, 0, 0, -3, -2]
 
p1 = 1
p2 = -2

print("Коэффициенты в многочлене Тейлора по степени x-1:", TaylorCoeffs(pol, p1))
print("Коэффициенты в многочлене Тейлора по степени x+2:", TaylorCoeffs(pol, p2))

С1

In [31]:
polc1 = [1,0,0,0,0,0,-1]

for i in np.roots(polc1):
    print(f"{i:.3f}")

-1.000+0.000j
-0.500+0.866j
-0.500-0.866j
0.500+0.866j
0.500-0.866j
1.000+0.000j


C2

In [33]:
polc21 = [1,1,1]
polc22 = [1,-1]

print(np.convolve(polc21,polc22))
print(np.polydiv(polc21,polc22))
print(poly_summ(polc21,polc22))

[ 1  0  0 -1]
(array([1., 2.]), array([3.]))
[1. 2. 0.]
